package id.my.myspotifyartists.model

object ArtistsData {
    var artists = listOf(
        Artist(
            1,
            "Olivia Rodrigo",
            "https://i.scdn.co/image/ab67616100005174e03a98785f3658f0b6461ec4",
            "57.403.721",
            "bad idea right? - 2023",
            "Olivia Isabel Rodrigo (born February 20, 2003) is an American singer-songwriter and actress. She gained recognition in the late 2010s with her lead roles on the Disney television programs Bizaardvark and High School Musical: The Musical: The Series. After signing with Geffen and Interscope Records in 2020, Rodrigo released her debut single \"Drivers License\", which broke various records and became one of the best-selling songs of 2021, propelling her to mainstream fame. She followed it up with singles \"Deja Vu\" and \"Good 4 U\", and released her debut solo studio album, Sour (2021), which was met with critical and commercial success, winning various accolades including three Grammy Awards. A Disney+ documentary, Olivia Rodrigo: Driving Home 2 U, chronicling her creative process with Sour, followed in 2022. Rodrigo has achieved three Billboard Hot 100 number-one singles, one Billboard 200 number-one album, and five multi-Platinum certifications by the Recording Industry Association of America (RIAA). In addition to other recognitions, she has won an American Music Award, seven Billboard Music Awards and three MTV Video Music Awards. Time named her the 2021 Entertainer of the Year and Billboard named her Woman of the Year in 2022. ",
            "https://i.scdn.co/image/ab67616d00001e028bfab8d577ad17a7b74d9f5f",
        ),
        Artist(
            2,
            "Reality Club",
            "https://i.scdn.co/image/ab67616100005174cb925d1cd51e4604cc97304d",
            "3.156.073",
            "Reality Club Presents… - 2023",
            "Take an indie–rock band and inject it with a firm attitude and catchy phrases, that\\'s Reality Club for you. Established in late 2016, Reality Club is an AMI (Anugerah Musik Indonesia) nominated indie band mogul who were nominated for best alternative track of the year and best newcomer of 2018. Formed in Jakarta, they have been ever-growing and catching people\\'s eyes and ears since their first release. They are Era Patigo on drums, Faiz Novascotia Saripudin on vocals and guitar, Fathia Izzati on vocals, and Nugi Wicaksono on bass. With eyes set on worldwide presence, they have started their expanse through Asia in 2019, playing in Tokyo and Singapore. Reality Club\'s work incorporates strong emotional messages through their sound and lyrics. As soon as you catch their tune, you will find yourself deeply immersed and vibing along to their songs because that\'s Reality Club for you. Don\'t believe it? See for yourself.",
            "https://i.scdn.co/image/ab67616d00001e02c607bcd8355681ab4fac2968",
            ),
        Artist(
            3,
            "Sheila On 7",
            "https://i.scdn.co/image/ab67616d00001e0254270208627aa8061a8abe21",
            "4.661.027",
            "Film Favorit - 2018",
            "Formed in Yogyakarta, Indonesia in 1996, Sheila on 7 was rock and pop band that underwent a number of line up changes in their decade-plus career. Shortly after forming, the group landed a deal with mega-label Sony, on which the band issued their debut album, Sheila on 7, in 1999. The self-titled debut was enough of a hit to warrant subsequent albums seeing release in neighboring countries, bringing the sound of Sheila on 7 to nations like Malaysia and Singapore. In 2005, Sheila on 7 released their first Best Of compilation, which was quickly followed by the full-length 507 a year later. In 2007, Sheila on 7\\'s music got an interesting interpretation with the compilation release, Sheila on 7 Karaoke Hits, Vol. 1. ~ Chris True, Rovi",
            "https://i.scdn.co/image/ab67616d00001e023d5137736fed4bdd05a92354",
            ),
        Artist(
            4,
            "NewJeans",
            "https://i.scdn.co/image/ab676161000051745da361915b1fa48895d4f23f",
            "25.693.704",
            "NewJeans 2nd EP \'Get Up\' - 2023",
            "NewJeans (MINJI, HANNI, DANIELLE, HAERIN, and HYEIN) made their debut on July 22, 2022 as the first group to debut from ADOR, an independent label under HYBE led by Hee Jin Min. The quintet aspires to push the limits of K-pop with honest and authentic music that exudes youth. Just like a pair of jeans that has been a staple of every wardrobe for generations, NewJeans aim to allure the listeners with timeless music to be kept in your daily music playlist. The act released New Jeans on August 1, 2022, instantly captivating the global audience and becoming the first K-pop band to achieve the million-seller milestone with their debut album. One of the title tracks “Hype Boy” charted on Billboard Global 200 for 37 consecutive weeks - the longest record from any K-pop female act. NewJeans continue to amaze the world with groundbreaking records while staying true to their musical flair and intrinsic charm, charting on Billboard Hot 100 within less than half a year of their debut with global smash hits “Ditto” and “OMG,” peaking at 74 and 82, respectively. NewJeans also broke the Guinness World Record as the fastest K-pop act to reach one billion streams on Spotify, further demonstrating their widespread global presence. Continuing their upward trajectory, NewJeans will make history as the first K-pop female band to perform at Lollapalooza in Chicago and Summer Sonic in Japan.",
            "https://i.scdn.co/image/ab67616d00001e020744690248ef3ba7b776ea7b",
            ),
        Artist(
            5,
            "Naura Ayu",
            "https://i.scdn.co/image/ab676161000051749d1b2aa04fab113893f437ba",
            "1.039.198",
            "Bye - 2023",
            "Adyla Rafa Naura Ayu (born June 18, 2005) is an Indonesian actress and singer. Following her mother\\'s career, Riafinola Ifani Sari, Naura became a child singer in 2014 with the release of her first studio album Dongeng which won the award for Best Children\\'s Album in the Anugerah Musik Indonesia 2015. Naura is the first Indonesian child singer to win the Triple Platinum award thanks to her fourth album, Katakanlah Cinta which has sold 500 thousand CDs. To date, Naura is the only child singer who has won the most awards for Best Child Solo Artist from the Anugerah Musik Indonesia, three times in 2016, 2018, and 2019. At the end of 2019, Naura ended her career as a child singer and rebranded herself as teenage singer marked by holding the Konser Dongeng 4 which was the closing of the Konser Dongeng since 2015. In early 2021, Naura released the single \"Kisah Kasih Sayang\" which is her first single as a teenage singer.",
            "https://i.scdn.co/image/ab67616d00001e0296bf24704f6fd7420092e040",
            ),
        Artist(
            6,
            "Hindia",
            "https://i.scdn.co/image/ab67616100005174324cea967a456ee680bf6b92",
            "7.141.449",
            "Lagipula Hidup Akan Berakhir - 2023",
            "Having finally brought .Feast  to the national level after years of hard work, in late 2018 Baskara Putra sowed the seeds for what would become his solo project Hindia. Following the low-key release of No One Will Find Me on a compilation EP and the Tidak Ada Salju Di Sini collaboration series of satirical seasonal songs, Hindia soon set about making his solo debut album. While the outbreak of COVID-19 brought live music events to a halt in 2020, Hindia remained productive throughout the pandemic. In addition to his own music, he recorded and released two EPs with .Feast and also established Lomba Sihir - consisting of Hindia and his live backing musicians - into a full-fledged band in its own right with the release of their album Selamat Datang di Ujung Dunia. Besides pursuing his own projects, Hindia is also an in-demand collaborator who has written, produced and/or appeared on tracks by a wide array of artists ranging from legends such as Iwan Fals, Dewa Budjana, Armand Maulana, to personal heroes including RAN and Pee Wee Gaskins, and also peers such as Laze and tradeto. With the return of live shows, you can now see Baskara Putra perform as Hindia, with .Feast and with Lomba Sihir. He is also busy putting the finishing touches on the second Hindia album, which is due for release in 2023.",
            "https://i.scdn.co/image/ab67616d00001e0249bdf0e981cbba25d48b44e0",
            ),
        Artist(
            7,
            "Tulus",
            "https://i.scdn.co/image/ab67616100005174b2dac5833519e3b4e5f7efdb",
            "9.117.492",
            "Manusia - 2022",
            "Tulus is an Indonesian singer-songwriter who runs his own label, TulusCompany. He was introduced to Indonesia’s music scene in 2011 with a debut album titled in his mononym, Tulus. The album earned the top spot in Rolling Stone Indonesia’s January and February 2012 listings. Over the span of ten years, Tulus has put his name among the A-lister Indonesian singers. His works have been widely appreciated among audiences from various segments, both in Indonesia as well as abroad. Tulus with TulusCompany released 5 successful albums called Tulus, Gajah, Monokrom, Langsung dari Konser Monokrom Jakarta (Live), and Manusia with line of songs that hit Indonesian charts, such as “Sewindu,” “Gajah,” “Pamit”, “Adaptasi” and “Hati-hati di Jalan”. All of his achievements and awards are proof that Tulus is a successful singer who has managed to penetrate the competitive music industry in Indonesia. Among them are “The Best Album of The Year” in 2015 for Gajah and in 2018 for Monokrom by Anugerah Musik Indonesia. He was also awarded as \"The Best Urban Soloist\" in 2017 and 2019.",
            "https://i.scdn.co/image/ab67616d00001e02b55d26c578e30129b0a7e86e",
            ),
        Artist(
            8,
            "MALIQ and D\'Essentials",
            "https://i.scdn.co/image/ab676161000051746f5044aae066797f015c74f3",
            "3.141.629",
            "The One (feat. Kara Chenoa) - 2023",
            "MALIQ and D\'Essentials was conceived on May 15, 2002 with 8 personnels under a genre they call Organic Music. The name MALIQ itself is an acronym from Music And Live Instrument Quality as the brainchild of brothers Angga and Widi Puradiredja (the group’s vocalist and drummer, respectively; as well as producer, composer and arranger for the group). The completion of the band became full circle with the presence of Indah and Dimi (vocals), Ifa (keys), Jawa (bass), Satrio (guitars) and Amar (horns). Later on, the group went through another change in their core personnel. After Dimi’s departure around 2006; Satrio, the group’s guitarist decided to leave and was quickly replaced by Arya Aditya Ramadhya, more widely known as “Lale”. Then on 2010, Ifa, the group’s keyboardist decided to leave and was replaced by Ilman Ibrahim Isa, more widely known as \"Ilman\". The group started out performing soul and soul-inspired music at different lounges and cafes in Jakarta. The first two years they went through was a solidification process for the group; as well as a way to introduce soul and/or soulful-inspired music to the Indonesian public; as it is yet to be widely known at the time of the group’s establishment.",
            "https://i.scdn.co/image/ab67616d00001e027e3a1f8e7af6392cee062343",
            ),
        Artist(
            9,
            "wave to earth",
            "https://i.scdn.co/image/ab67616100005174c3c28df50abf70a11d9f8063",
            "6.228.754",
            "0.1 flaws and all. - 2023",
            "Based in Seoul, South Korea, \'Wave to Earth\' is a three-member band consisting of singer-songwriter Daniel Kim, drummer Dong Kyu Shin, and bassist John Cha. \'Wave to Earth\' produces indie pop with a lo-fi sound based on jazz drumming, creating a unique sense of the seasons and a dreamy atmosphere in the music. With the primary motto of \"All Self-made,\" all recording, mixing, and mastering is done directly by the band members, who also direct the overall art field, such as album art, video, and fashion. \'Wave to Earth\' debuted with the single \'wave\' in 2019, followed by EPs \'wave 0.01\' and \'summer flows 0.02\'. After joining the \'Wavy Seoul\' label, they released singles \'nouvelle vague\' and \'calla.\' The name \'Wave to Earth\' reveals the band\'s desire to \"become the new wave\" and expand its own universe across the world.",
            "https://i.scdn.co/image/ab67616d00001e02c21555708975ad94b1faf422",
            ),
        Artist(
            10,
            "Nadin Amizah",
            "https://i.scdn.co/image/ab67616100005174ff2b0b6741e266b890785371",
            "9.356.387",
            "Tawa - 2023",
            "Spending her teenage years feeling isolated from the outside world, Nadin Amizah began her song-writing journey before her 17th birthday. What started as her way of putting whatever her feelings are into good use, Nadin continues singing and taking little but sure steps into the magical musical world, making friends and new stories to unfold. Nadin writes only what she feels. She will lay whatever feels like a knot on her chest or throat down on a paper or notes, carefully choosing words to describe the unsaid. She often writes about her rampant journey on finding the true meaning of the word love, divorces she had witnessed throughout her entire short-lived life, her dreams, her imaginations, her mother, her family, and all the people who has touched souls with her along her way. Nadin gifts her surroundings with raw and unfiltered emotions. Making them who crave for their voices to be sung feel attracted to her, as they feel represented. With her lyrics, Nadin wished to be known as the little girl who sings an old man poem, ripe before time, and mature in her own way. Debuted with her song ‘Rumpang’, she later surprised her listeners with a self-written and collectively-produced album titled ‘Selamat Ulang Tahun’ released exactly on her 20th birthday. With 10 songs in which she storytells about her confusing teenage years and her mixed feelings about growing up and outgrowing everything. Nadin will continue telling her story to those who listens carefully.",
            "https://i.scdn.co/image/ab67616d00001e0204f7230f35d3cf039330ca2d",
            ),
    )
}